{{- if .Values.enabled }}

apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name  }}
  namespace: {{ .Chart.Name  }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name  }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.ports.http }}
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ .Chart.Name  }}
{{- end }}