{{- if .Values.enabled }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
  namespace: plex
spec:
  selector:
    matchLabels:
      app: plex
  template:
    metadata:
      labels:
        app: plex
    spec:
      containers:
        - name: plex
          env:
            - name: PUID
              value: {{.Values.securityContext.runAsUser}}
            - name: PGID
              value: {{.Values.securityContext.runAsGroup}}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.version }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /identity
              port: {{ .Values.port }}
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /identity
              port: {{ .Values.port }}
            initialDelaySeconds: 3
            periodSeconds: 3
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
{{- end }}