{{- if .Values.enabled }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name  }}
  namespace: {{ .Chart.Name  }}
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name  }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name  }}
    spec:
      containers:
        - name: {{ .Chart.Name  }}
          # Couldn't get this working on k3s running in a VM - try again running on metal? Seemed to be an image problem.

          #env:
          #  - name: PUID
          #    value: "{{.Values.securityContext.runAsUser}}"
          #  - name: PGID
          #    value: "{{.Values.securityContext.runAsGroup}}"
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.version }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /identity
              port: {{ .Values.port }}
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /identity
              port: {{ .Values.port }}
            initialDelaySeconds: 3
            periodSeconds: 3
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
{{- end }}